"""Catálogo de juegos de conversación para grupos. Cada juego pertenece a una
categoría y tiene una lista de prompts (preguntas/consignas) que se muestran
uno a la vez, en orden aleatorio sin repetir hasta agotar la lista. Contenido
divertido y a veces vergonzoso, pero nunca de tipo sexual."""

CATEGORIAS = [
    {"id": "rapidas", "nombre": "⚡ Preguntas rápidas y curiosas"},
    {"id": "hipoteticos", "nombre": "🤔 Qué harías si..."},
    {"id": "dilemas", "nombre": "⚖️ Esto o aquello"},
    {"id": "verdad", "nombre": "🙊 Verdad"},
    {"id": "debate", "nombre": "🗣️ Debate y opinión"},
    {"id": "creatividad", "nombre": "🎭 Rol y creatividad"},
    {"id": "conocerse", "nombre": "💛 Conócete mejor"},
    {"id": "ingenio", "nombre": "🧠 Ingenio y rapidez"},
    {"id": "memoria", "nombre": "🔍 Memoria y observación"},
    {"id": "fe", "nombre": "🕊️ Fe y reflexión"},
]

JUEGOS = {
    "rapidas_ronda_relampago": {
        "categoria": "rapidas",
        "titulo": "Ronda relámpago",
        "prompts": [
            "¿Cuál es la última canción que se te quedó pegada en la cabeza?",
            "¿Qué comerías ahora mismo si pudieras pedir cualquier cosa?",
            "¿Cuál fue la última mentira piadosa que dijiste?",
            "¿Qué app tienes más abierta en el celular ahora mismo?",
            "¿Cuál es tu emoji más usado?",
            "¿A qué hora te fuiste a dormir anoche, de verdad?",
            "¿Cuál es la última foto vergonzosa que tomaste sin querer?",
            "¿Qué serie ves y te da pena admitir que te gusta?",
            "¿Cuál fue tu último 'ya se me olvidó lo que iba a decir'?",
            "¿Qué cosa random tienes en el bolsillo o la cartera ahora?",
        ],
    },
    "rapidas_ruleta_curiosidad": {
        "categoria": "rapidas",
        "titulo": "La ruleta de la curiosidad",
        "prompts": [
            "Dato: los pulpos tienen tres corazones. ¿Qué opinas de ellos?",
            "Dato: la miel nunca se echa a perder. ¿La probaste vencida sin saberlo alguna vez?",
            "Dato: bostezar es contagioso. ¿Acabas de bostezar leyendo esto?",
            "Dato: el corazón de una ballena azul pesa como un carro. ¿Te da miedo el mar?",
            "Dato: no puedes estornudar con los ojos abiertos. ¿Lo intentaste ahora?",
            "Dato: los plátanos son técnicamente bayas. ¿Qué otra 'verdad random' conoces?",
            "Dato: el hipo dura en promedio 5 minutos. ¿Cuál fue tu peor ataque de hipo?",
            "Dato: hay más estrellas que granos de arena en la Tierra. ¿Te da vértigo pensarlo?",
            "Dato: los gatos no pueden saborear lo dulce. ¿Qué animal te gustaría ser por un día?",
            "Dato: el cerebro humano no siente dolor directamente. ¿Sabías eso?",
        ],
    },
    "rapidas_bingo_respuestas": {
        "categoria": "rapidas",
        "titulo": "Bingo de respuestas",
        "prompts": [
            "Nombra rápido: tu color favorito, tu animal favorito y tu comida favorita.",
            "Nombra rápido: un miedo tonto, una manía y un talento oculto.",
            "Nombra rápido: tu palabra favorita, una que odies y una que inventarías.",
            "Nombra rápido: un lugar al que volverías, uno que no repetirías y uno soñado.",
            "Nombra rápido: tu app favorita, la más inútil que tienes y la que borrarías.",
            "Nombra rápido: una canción feliz, una triste y una vergonzosa que amas.",
            "Nombra rápido: tu excusa favorita, tu chiste malo favorito y tu apodo de niño.",
            "Nombra rápido: algo que coleccionas, algo que tirarías y algo que atesoras.",
            "Nombra rápido: tu snack favorito, el más raro que probaste y el que odias.",
            "Nombra rápido: una serie, una película y un libro que marcaron tu infancia.",
        ],
    },
    "rapidas_interrogatorio_expres": {
        "categoria": "rapidas",
        "titulo": "El interrogatorio exprés",
        "prompts": [
            "¿Última vez que lloraste de risa? Cuenta qué pasó.",
            "¿Última vez que te caíste en público?",
            "¿Última vez que confundiste a alguien con otra persona?",
            "¿Última vez que mandaste un mensaje a la persona equivocada?",
            "¿Última vez que te quedaste dormido en un lugar inapropiado?",
            "¿Última vez que hablaste solo en voz alta sin querer que te oyeran?",
            "¿Última vez que te reíste en un momento serio y no podías parar?",
            "¿Última vez que se te trabó una palabra hablando con alguien que te gustaba o admirabas?",
            "¿Última vez que llegaste tarde y la excusa fue ridícula?",
            "¿Última vez que cantaste en la ducha o el carro a todo volumen?",
        ],
    },
    "rapidas_capsula_tiempo": {
        "categoria": "rapidas",
        "titulo": "La cápsula del tiempo",
        "prompts": [
            "¿Qué te gustaba hace 10 años que hoy te da vergüenza?",
            "¿Qué peinado o estilo tuviste que hoy no repetirías jamás?",
            "¿Qué banda o cantante te encantaba y hoy casi ni recuerdas?",
            "¿Qué creías de niño que resultó ser completamente falso?",
            "¿Qué frase repetías todo el tiempo de adolescente?",
            "¿Cuál fue tu primer 'crush' vergonzoso de la infancia?",
            "¿Qué apodo tenías que preferirías olvidar?",
            "¿Qué jurabas que ibas a ser de grande y no fue así?",
            "¿Qué foto de perfil vieja te daría pena que alguien encontrara?",
            "¿Qué manía de niño todavía conservas en secreto?",
        ],
    },
    "rapidas_termometro": {
        "categoria": "rapidas",
        "titulo": "El termómetro",
        "prompts": [
            "Del 1 al 10, ¿qué tan desordenado eres? Explica el número.",
            "Del 1 al 10, ¿qué tan dramático te pones cuando te enfermas?",
            "Del 1 al 10, ¿qué tan bueno cocinando eres? Sé honesto.",
            "Del 1 al 10, ¿qué tan celoso o celosa puedes ser?",
            "Del 1 al 10, ¿qué tan puntual eres realmente?",
            "Del 1 al 10, ¿qué tan buen mentiroso eres jugando cartas o juegos de mesa?",
            "Del 1 al 10, ¿qué tan valiente eres para hablar en público?",
            "Del 1 al 10, ¿qué tan 'stalker' eres en redes sociales?",
            "Del 1 al 10, ¿qué tan bien bailas? Y ahora, ¿qué tan bien crees que bailas?",
            "Del 1 al 10, ¿qué tan fácil es hacerte reír?",
        ],
    },
    "rapidas_pregunta_libre": {
        "categoria": "rapidas",
        "titulo": "Pregúntame lo que quieras",
        "prompts": [
            "¿Qué cosa haces cuando nadie te ve que jamás admitirías en público?",
            "¿Cuál es tu 'guilty pleasure' más vergonzoso?",
            "¿Qué palabra usas mal desde siempre y nadie te corrigió a tiempo?",
            "¿Cuál es la cosa más random que atesoras sin razón aparente?",
            "¿Qué costumbre tuya considerarían rara tus amigos?",
            "¿Cuál ha sido tu peor corte de pelo?",
            "¿Qué cosa dijiste una vez que te persigue hasta hoy?",
            "¿Cuál es tu talento inútil pero curioso?",
            "¿Qué comida rara te gusta que a nadie más le gusta?",
            "¿Cuál ha sido tu excusa más creativa para no ir a algo?",
        ],
    },
    "rapidas_lista_de_tres": {
        "categoria": "rapidas",
        "titulo": "La lista de los 3",
        "prompts": [
            "3 lugares que quieres visitar antes de morir.",
            "3 cosas que harías si fueras invisible por un día.",
            "3 personas (vivas o no) con las que cenarías.",
            "3 cosas vergonzosas que has hecho por amor o amistad.",
            "3 palabras que usarías para describir tu adolescencia.",
            "3 cosas que siempre llevas encima aunque no las necesites.",
            "3 momentos en los que quisiste que la tierra te tragara.",
            "3 series o películas que verías una y otra vez sin cansarte.",
            "3 cosas que extrañas de ser niño.",
            "3 apodos que te han puesto en la vida.",
        ],
    },
    "rapidas_manantial_curiosidades": {
        "categoria": "rapidas",
        "titulo": "El manantial de curiosidades",
        "prompts": [
            "¿Cuál es la mentira más grande que te han creído?",
            "¿Cuál es el rumor más raro que han inventado sobre ti?",
            "¿Qué cosa haces distinto a como la hace todo el mundo?",
            "¿Cuál ha sido tu peor regalo dado o recibido?",
            "¿Qué cosa tuya la gente describiría como 'muy tú'?",
            "¿Cuál es tu ritual raro antes de dormir?",
            "¿Qué costumbre familiar te parece rara vista desde afuera?",
            "¿Cuál fue tu peor decisión de moda?",
            "¿Qué cosa comprarías sin dudar si tuvieras dinero ilimitado?",
            "¿Cuál es tu mayor contradicción como persona?",
        ],
    },
    "rapidas_si_o_no": {
        "categoria": "rapidas",
        "titulo": "Sí o No relámpago",
        "prompts": [
            "¿Alguna vez fingiste estar enfermo para faltar a algo?",
            "¿Alguna vez espiaste el celular de alguien?",
            "¿Alguna vez te reíste en un funeral o momento serio sin querer?",
            "¿Alguna vez copiaste en un examen?",
            "¿Alguna vez te enamoraste de alguien que no debías?",
            "¿Alguna vez lloraste viendo una película animada?",
            "¿Alguna vez dijiste 'te quiero' sin sentirlo del todo?",
            "¿Alguna vez te hiciste el dormido para no hablar con alguien?",
            "¿Alguna vez cantaste karaoke sabiendo que cantas mal?",
            "¿Alguna vez te comiste algo que se cayó al piso sin dudarlo?",
        ],
    },
    "hipoteticos_clasico": {
        "categoria": "hipoteticos",
        "titulo": "¿Qué harías si...? clásico",
        "prompts": [
            "¿Qué harías si se te olvidara el nombre de alguien justo al presentarlo?",
            "¿Qué harías si se te rompieran los pantalones en público?",
            "¿Qué harías si te llamaran por el nombre de tu ex sin querer?",
            "¿Qué harías si te quedaras encerrado en un baño público?",
            "¿Qué harías si se te cayera el celular al inodoro?",
            "¿Qué harías si tropezaras subiendo a un escenario frente a todos?",
            "¿Qué harías si te descubrieran hablando solo?",
            "¿Qué harías si te confundieran con alguien famoso?",
            "¿Qué harías si se te quedara comida entre los dientes toda una reunión?",
            "¿Qué harías si accidentalmente le dieras 'me gusta' a una foto vieja de alguien que te gusta?",
        ],
    },
    "hipoteticos_otra_vida": {
        "categoria": "hipoteticos",
        "titulo": "Un día en otra vida",
        "prompts": [
            "¿Qué harías si fueras el presidente de tu país por un día?",
            "¿Qué harías si fueras tu mascota (o la mascota de un amigo) por un día?",
            "¿Qué harías si fueras un profesor de tu peor materia por un día?",
            "¿Qué harías si fueras millonario de repente, solo por hoy?",
            "¿Qué harías si fueras del sexo opuesto por un día?",
            "¿Qué harías si fueras un influencer famoso por un día?",
            "¿Qué harías si fueras el jefe de tu trabajo o colegio por un día?",
            "¿Qué harías si fueras invisible en tu propia casa por un día?",
            "¿Qué harías si fueras un superhéroe sin ningún poder útil por un día?",
            "¿Qué harías si fueras tú mismo pero 20 años mayor, por un día?",
        ],
    },
    "hipoteticos_boton_magico": {
        "categoria": "hipoteticos",
        "titulo": "El botón mágico",
        "prompts": [
            "Hay un botón que borra un recuerdo vergonzoso tuyo para siempre. ¿Lo presionas? ¿Cuál borrarías?",
            "Hay un botón que te hace decir siempre la verdad por 24 horas. ¿Lo presionas?",
            "Hay un botón que intercambia tu voz con la de alguien del grupo por un día. ¿Lo presionas?",
            "Hay un botón que hace que todos bailen sin poder parar por 1 minuto. ¿Lo presionas ahora?",
            "Hay un botón que revela el último mensaje que borraste. ¿Lo presionas?",
            "Hay un botón que te da el don de cantar perfecto, pero solo en público. ¿Lo presionas?",
            "Hay un botón que congela el tiempo por una hora solo para ti. ¿Qué harías con ella?",
            "Hay un botón que hace que digas en voz alta tu pensamiento más random ahora mismo. ¿Lo presionas?",
            "Hay un botón que te teletransporta a un lugar al azar del mundo ahora mismo. ¿Lo presionas?",
            "Hay un botón que borra una app de tu celular para siempre. ¿Cuál elegirías borrar?",
        ],
    },
    "hipoteticos_superpoder_sorpresa": {
        "categoria": "hipoteticos",
        "titulo": "Superpoder sorpresa",
        "prompts": [
            "Tienes el poder de saber cuándo alguien miente, pero solo por hoy. ¿Qué harías?",
            "Tienes el poder de teletransportarte, pero solo a lugares donde ya estuviste. ¿A dónde vas?",
            "Tienes el poder de leer la mente, pero solo de animales. ¿Qué animal escuchas primero?",
            "Tienes súper fuerza pero solo cuando nadie te está mirando. ¿Qué harías con eso?",
            "Tienes el poder de volar, pero muy lento, como caminando en el aire. ¿Lo usarías?",
            "Tienes el poder de hacerte invisible, pero solo pierdes la ropa también. ¿Lo usarías?",
            "Tienes el poder de hablar todos los idiomas, pero solo cantando. ¿Qué dirías primero?",
            "Tienes el poder de retroceder el tiempo 10 segundos, una sola vez al día. ¿Cuándo lo usarías?",
            "Tienes el poder de hacer reír a cualquiera, pero solo con chistes malísimos. ¿Lo usarías igual?",
            "Tienes un poder random que ni tú entiendes bien. Descríbelo e inventa cómo lo usarías.",
        ],
    },
    "hipoteticos_viaje_tiempo": {
        "categoria": "hipoteticos",
        "titulo": "El viaje en el tiempo",
        "prompts": [
            "Si pudieras volver a tu yo de 10 años, ¿qué le dirías?",
            "Si pudieras viajar a hace 100 años, ¿a dónde y por qué?",
            "Si pudieras ver tu futuro dentro de 20 años por un minuto, ¿lo harías?",
            "Si pudieras revivir un solo día de tu vida exactamente igual, ¿cuál sería?",
            "Si pudieras avisarle algo a la humanidad de hace 500 años, ¿qué sería?",
            "Si pudieras deshacer una sola decisión de tu vida, ¿cuál sería (sin decir por qué si prefieres)?",
            "Si pudieras viajar al futuro y volver, pero solo recordando una cosa, ¿qué elegirías recordar?",
            "Si pudieras cambiar de época para vivir, ¿cuál elegirías?",
            "Si pudieras hablar contigo mismo de hace 5 años por 5 minutos, ¿qué le preguntarías?",
            "Si pudieras congelar este momento exacto para siempre, ¿lo harías?",
        ],
    },
    "hipoteticos_isla_desierta": {
        "categoria": "hipoteticos",
        "titulo": "La isla desierta",
        "prompts": [
            "Naufragas en una isla desierta: ¿qué 3 cosas de tu bolsillo/cartera te salvarían?",
            "Solo puedes llevar una persona del grupo a la isla contigo. ¿A quién y por qué?",
            "En la isla solo hay un tipo de comida para siempre. ¿Cuál eliges?",
            "Puedes llevar solo un libro a la isla. ¿Cuál sería?",
            "En la isla puedes hablar con un solo animal. ¿Cuál eliges y qué le preguntas?",
            "Tienes que sobrevivir un mes en la isla solo con lo que llevas puesto ahora. ¿Cómo te va?",
            "En la isla encuentras una caja con una sola cosa útil. ¿Qué esperas que sea?",
            "Puedes mandar un solo mensaje desde la isla antes de quedarte sin señal. ¿A quién y qué dices?",
            "En la isla solo puedes escuchar una canción en bucle para siempre. ¿Cuál eliges?",
            "Te rescatan después de un año en la isla. ¿Qué es lo primero que haces al llegar a casa?",
        ],
    },
    "hipoteticos_millon_inesperado": {
        "categoria": "hipoteticos",
        "titulo": "El millón inesperado",
        "prompts": [
            "Te ganas la lotería mañana. ¿Qué es lo primero que compras, sin pensarlo?",
            "Un familiar lejano te deja una herencia enorme. ¿En qué la gastarías primero?",
            "Te dan un millón de dólares pero debes gastarlo todo en 24 horas. ¿Qué haces?",
            "Te ganas un dinero inesperado, pero debes darle la mitad a alguien del grupo. ¿A quién?",
            "Con dinero ilimitado, ¿qué negocio absurdo abrirías solo por diversión?",
            "Te regalan una casa, pero en el lugar más random del mundo. ¿A dónde esperas que sea?",
            "Ganas dinero suficiente para no trabajar nunca más. ¿En qué ocuparías tus días?",
            "Te dan a elegir entre un millón hoy o diez millones en 10 años. ¿Qué eliges y por qué?",
            "Con ese dinero inesperado, ¿le comprarías algo vergonzoso a alguien del grupo? ¿Qué?",
            "Si ese dinero viniera con una condición rara (como usar sombrero todos los días), ¿la aceptarías?",
        ],
    },
    "hipoteticos_cambia_cuerpo": {
        "categoria": "hipoteticos",
        "titulo": "Cambia de cuerpo",
        "prompts": [
            "Despiertas en el cuerpo de otra persona del grupo por un día. ¿Qué es lo primero que haces?",
            "Si intercambiaras cuerpo con tu mejor amigo, ¿qué cosa suya cambiarías primero?",
            "Estás en el cuerpo de alguien famoso por un día. ¿A quién elegirías?",
            "Despiertas en el cuerpo de tu yo del futuro. ¿Qué esperas ver?",
            "Estás en el cuerpo de tu mascota por un día. ¿Qué harías primero?",
            "Cambias de cuerpo con alguien de otra generación (abuelo/nieto). ¿Cómo sería tu día?",
            "Despiertas en el cuerpo de un desconocido random en la calle. ¿Qué harías?",
            "Si pudieras copiar el cuerpo de alguien solo por un talento suyo, ¿de quién y cuál talento?",
            "Estás en el cuerpo de alguien del grupo justo antes de un examen o entrevista suya. ¿Qué haces?",
            "Vuelves a tu cuerpo, pero con un recuerdo vergonzoso del otro cuerpo. ¿Lo cuentas o lo guardas?",
        ],
    },
    "hipoteticos_fin_del_mundo": {
        "categoria": "hipoteticos",
        "titulo": "El fin del mundo (versión ligera)",
        "prompts": [
            "Si el mundo se acabara en una semana, ¿qué harías el primer día?",
            "Si solo pudieras salvar tres objetos de tu casa, ¿cuáles serían?",
            "Si tuvieras que mandar un mensaje final a todos tus contactos, ¿qué dirías?",
            "Si el fin del mundo fuera en 24 horas, ¿a quién llamarías primero?",
            "Si solo pudieras comer una comida más en tu vida, ¿cuál sería?",
            "Si tuvieras que elegir con quién pasar tus últimas horas, ¿con quién sería?",
            "Si el mundo se acabara mañana, ¿qué cosa pendiente resolverías hoy mismo?",
            "Si pudieras salvar un solo recuerdo de la humanidad, ¿cuál sería?",
            "Si supieras que es tu último día, ¿qué le dirías a alguien del grupo ahora mismo?",
            "Si el apocalipsis empezara ahora, ¿quién del grupo sobreviviría más tiempo y por qué?",
        ],
    },
    "hipoteticos_deseo_condicion": {
        "categoria": "hipoteticos",
        "titulo": "Un deseo, una condición",
        "prompts": [
            "Te conceden un deseo, pero debes cantar en público cada vez que lo uses. ¿Lo pides igual?",
            "Puedes ser más inteligente, pero olvidas un recuerdo feliz al azar. ¿Aceptas?",
            "Puedes tener el trabajo de tus sueños, pero debes usar un disfraz ridículo cada día. ¿Aceptas?",
            "Puedes viajar gratis a donde quieras, pero solo en pijama. ¿Aceptas?",
            "Puedes tener más dinero, pero todos sabrán tu contraseña de siempre. ¿Aceptas?",
            "Puedes ser famoso, pero solo por algo vergonzoso que hiciste una vez. ¿Aceptas?",
            "Puedes tener un talento nuevo, pero debes demostrarlo ahora mismo frente al grupo. ¿Aceptas?",
            "Puedes ganar cualquier discusión siempre, pero pierdes el sentido del humor. ¿Aceptas?",
            "Puedes tener la casa de tus sueños, pero con un color que odias por fuera. ¿Aceptas?",
            "Puedes cumplir tu deseo más grande, pero debes contárselo a todo el grupo ahora. ¿Lo dices?",
        ],
    },
    "dilemas_esto_o_lo_otro": {
        "categoria": "dilemas",
        "titulo": "Esto o lo otro",
        "prompts": [
            "¿Playa o montaña?",
            "¿Ducha en la mañana o en la noche?",
            "¿Comida dulce o comida salada, para siempre?",
            "¿Ser siempre 10 minutos tarde o siempre 30 minutos temprano?",
            "¿Perder el celular o perder la cartera (sin plata dentro)?",
            "¿Vivir sin música o vivir sin películas?",
            "¿Hablar demasiado o hablar muy poco, para siempre?",
            "¿Tener que cantar o tener que bailar cada vez que entras a un lugar?",
            "¿Vivir en el pasado o en el futuro?",
            "¿Ser el más gracioso o el más inteligente del grupo?",
        ],
    },
    "dilemas_imposible": {
        "categoria": "dilemas",
        "titulo": "El dilema imposible",
        "prompts": [
            "¿Perder todos tus recuerdos felices o todos los tristes?",
            "¿Saber cuándo vas a morir o cómo vas a morir?",
            "¿Ser increíblemente famoso pero infeliz, o anónimo pero feliz?",
            "¿Decir siempre lo que piensas o nunca poder decir lo que piensas?",
            "¿Vivir 100 años solo, o 60 años acompañado?",
            "¿Tener éxito pero sin nadie que lo celebre contigo, o fracasar acompañado?",
            "¿Saber toda la verdad siempre o vivir feliz sin saber ciertas cosas?",
            "¿Perder la vista o el oído?",
            "¿Repetir el mejor día de tu vida para siempre, o vivir días distintos sin saber si serán buenos?",
            "¿Tener una vida perfecta pero corta, o una vida normal pero larga?",
        ],
    },
    "dilemas_elige_bando": {
        "categoria": "dilemas",
        "titulo": "Elige tu bando",
        "prompts": [
            "¿Perros o gatos?",
            "¿Café o té?",
            "¿Fiestas grandes o reuniones pequeñas?",
            "¿Netflix o cine?",
            "¿Mensajes de texto o llamadas?",
            "¿Verano o invierno?",
            "¿Ciudad o pueblo?",
            "¿Desayuno dulce o desayuno salado?",
            "¿Madrugar o trasnochar?",
            "¿Planear todo o improvisar todo?",
        ],
    },
    "dilemas_la_balanza": {
        "categoria": "dilemas",
        "titulo": "La balanza",
        "prompts": [
            "¿Tener mucho tiempo libre pero poco dinero, o mucho dinero pero poco tiempo libre?",
            "¿Un trabajo que odias pero bien pagado, o uno que amas pero mal pagado?",
            "¿Tener muchos amigos superficiales, o pocos amigos muy cercanos?",
            "¿Ser muy exitoso pero criticado, o promedio pero querido por todos?",
            "¿Viajar mucho pero solo, o viajar poco pero siempre acompañado?",
            "¿Tener el cuerpo que quieres pero odiar tu trabajo, o al revés?",
            "¿Ser el líder con toda la presión, o el segundo al mando sin tanta responsabilidad?",
            "¿Vivir cómodo sin sorpresas, o vivir con aventuras pero inestabilidad?",
            "¿Tener razón siempre pero solo, o equivocarte a veces pero acompañado?",
            "¿Saber mucho de un solo tema, o un poco de todos los temas?",
        ],
    },
    "dilemas_nunca_mas_uno": {
        "categoria": "dilemas",
        "titulo": "Nunca más uno de los dos",
        "prompts": [
            "¿Renunciar para siempre al chocolate o al queso?",
            "¿Renunciar para siempre a las redes sociales o a la televisión?",
            "¿Renunciar para siempre a viajar en avión o a manejar carro?",
            "¿Renunciar para siempre a la música o a las películas?",
            "¿Renunciar para siempre a dormir siesta o a trasnochar?",
            "¿Renunciar para siempre a los mensajes de voz o a las videollamadas?",
            "¿Renunciar para siempre al picante o al dulce?",
            "¿Renunciar para siempre a hacer ejercicio o a comer afuera?",
            "¿Renunciar para siempre a los emojis o a los memes?",
            "¿Renunciar para siempre a cocinar o a lavar los platos (alguien más lo hace siempre)?",
        ],
    },
    "dilemas_superlativos": {
        "categoria": "dilemas",
        "titulo": "Superlativos de grupo",
        "prompts": [
            "¿Quién del grupo sobreviviría más tiempo en una isla desierta?",
            "¿Quién del grupo se haría famoso primero, y por qué motivo probablemente vergonzoso?",
            "¿Quién del grupo lloraría primero viendo una película triste?",
            "¿Quién del grupo se perdería más fácil en una ciudad nueva?",
            "¿Quién del grupo ganaría un concurso de baile sin haber practicado?",
            "¿Quién del grupo tardaría más en responder un mensaje?",
            "¿Quién del grupo sería el mejor mintiendo en un juego de mesa?",
            "¿Quién del grupo organizaría mejor una fiesta sorpresa?",
            "¿Quién del grupo se comería algo raro primero por una apuesta?",
            "¿Quién del grupo dormiría más tiempo si nadie lo despertara?",
        ],
    },
    "dilemas_semaforo": {
        "categoria": "dilemas",
        "titulo": "El semáforo de decisiones",
        "prompts": [
            "¿Contestar una llamada random de un número desconocido, o dejarla ir a buzón?",
            "¿Comer algo que se te cayó al piso (5 segundos) o quedarte con hambre?",
            "¿Usar la misma ropa dos días seguidos sin que nadie note, o lavarla cada noche?",
            "¿Decir una mentira pequeña para no herir, o decir siempre la verdad aunque duela?",
            "¿Cancelar un plan a última hora, o ir aunque no tengas ganas?",
            "¿Hablarle primero a alguien que te gusta, o esperar a que hable primero?",
            "¿Pedir ayuda cuando la necesitas, o intentar resolverlo solo primero?",
            "¿Salir de tu zona de confort ahora mismo, o quedarte cómodo?",
            "¿Confesar algo vergonzoso a cambio de un beneficio, o guardarlo para siempre?",
            "¿Cambiar de tema cuando algo te incomoda, o enfrentarlo directamente?",
        ],
    },
    "dilemas_moneda_al_aire": {
        "categoria": "dilemas",
        "titulo": "La moneda al aire",
        "prompts": [
            "¿Empezar de cero en otra ciudad, o quedarte donde estás siempre?",
            "¿Tener un año libre sin trabajar (con lo básico cubierto), o un ascenso ahora mismo?",
            "¿Aprender un idioma nuevo perfectamente, o un instrumento musical perfectamente?",
            "¿Ser recordado por algo grande dentro de 100 años, o vivir feliz y anónimo?",
            "¿Tener el poder de deshacer un error, o el poder de predecir uno futuro?",
            "¿Vivir sin internet un mes, o vivir sin salir de casa un mes (con internet)?",
            "¿Que todos sepan lo que piensas siempre, o que nadie sepa nunca lo que sientes?",
            "¿Ganar cada discusión, o tener siempre la última palabra en broma?",
            "¿Un viaje pagado a cualquier parte, o pagar todas tus deudas de una vez?",
            "¿Tener un don artístico, o un don para los negocios?",
        ],
    },
    "dilemas_menu_imposible": {
        "categoria": "dilemas",
        "titulo": "El menú imposible",
        "prompts": [
            "¿Comer pizza con piña para siempre, o nunca más comer pizza?",
            "¿Comer siempre comida fría, o siempre comida sin sal?",
            "¿Tomar solo agua el resto de tu vida, o solo jugos (nada de gaseosa ni café)?",
            "¿Comer tu plato favorito todos los días por un año, o no comerlo nunca más?",
            "¿Cocinar siempre tú, o que alguien más cocine pero elige mal siempre?",
            "¿Comer en silencio siempre, o comer siempre con ruido de fondo molesto?",
            "¿Un buffet ilimitado pero de comida que no te gusta, o un plato pequeño de tu favorita?",
            "¿Comer rápido siempre, o comer lento siempre?",
            "¿Nunca más postre, o nunca más comida frita?",
            "¿Cenar solo una vez a la semana con toda tu familia, o nunca cenar con ellos pero verlos seguido?",
        ],
    },
    "dilemas_prefiero_perder": {
        "categoria": "dilemas",
        "titulo": "Prefiero perder A que perder B",
        "prompts": [
            "¿Prefieres perder tu álbum de fotos de la infancia o tu diario/notas personales?",
            "¿Prefieres perder tu canción favorita para siempre o tu película favorita para siempre?",
            "¿Prefieres perder la habilidad de correr o la de nadar?",
            "¿Prefieres perder un recuerdo feliz al azar o un objeto de valor sentimental?",
            "¿Prefieres perder tu sentido del olfato o del gusto?",
            "¿Prefieres perder tu celular actual con todo dentro, o empezar de cero en un lugar nuevo?",
            "¿Prefieres perder la posibilidad de viajar lejos o la de mudarte de casa alguna vez?",
            "¿Prefieres perder una amistad superficial o una discusión importante que tenías pendiente?",
            "¿Prefieres perder tu comida favorita para siempre o tu bebida favorita para siempre?",
            "¿Prefieres perder un día libre a la semana o una hora de sueño cada noche?",
        ],
    },
    "verdad_sincera": {
        "categoria": "verdad",
        "titulo": "Verdad sincera",
        "prompts": [
            "¿Cuál es el apodo más vergonzoso que te han puesto?",
            "¿Cuál ha sido tu peor 'ghosting' dado o recibido?",
            "¿Cuál es la cosa más tonta por la que has llorado?",
            "¿Qué mentira le dices a tu familia sobre tus planes casi siempre?",
            "¿Cuál es tu miedo más irracional?",
            "¿Cuál ha sido tu peor cita o encuentro social?",
            "¿Qué cosa haces para sentirte bien que te daría pena admitir?",
            "¿Cuál es la búsqueda más rara que has hecho en internet?",
            "¿Qué manía tuya molesta a los demás y no piensas dejar?",
            "¿Cuál es el cumplido que más te ha costado creer sobre ti?",
        ],
    },
    "verdad_secreto_ligero": {
        "categoria": "verdad",
        "titulo": "El secreto ligero",
        "prompts": [
            "Cuenta algo de ti que muy pocos amigos saben.",
            "Cuenta un hábito raro que tienes cuando estás solo.",
            "Cuenta algo que finges que te gusta pero en realidad no.",
            "Cuenta algo que odias hacer pero haces por quedar bien.",
            "Cuenta una manía tuya relacionada con la limpieza o el orden.",
            "Cuenta algo que te da vergüenza que te guste tanto.",
            "Cuenta un miedo pequeño que nunca le has contado a nadie del grupo.",
            "Cuenta algo que sueles hacer y crees que nadie nota.",
            "Cuenta una costumbre familiar que solo tu familia entendería.",
            "Cuenta algo que compraste por impulso y te arrepientes un poco.",
        ],
    },
    "verdad_confesion_curiosa": {
        "categoria": "verdad",
        "titulo": "La confesión curiosa",
        "prompts": [
            "¿Cuál es tu manía más rara comiendo?",
            "¿Qué te da miedo sin razón lógica (arañas, oscuridad, algo random)?",
            "¿Qué cosa random te hace ilusión que a otros no?",
            "¿Cuál es el objeto más inútil que guardas con cariño?",
            "¿Qué costumbre extraña tienes al dormir?",
            "¿Cuál es tu superstición más rara?",
            "¿Qué cosa cotidiana haces distinto a como la hace todo el mundo?",
            "¿Cuál es tu 'ritual' antes de algo importante?",
            "¿Qué comida rara mezclas que otros consideran asqueroso?",
            "¿Cuál es tu manía revisando el celular?",
        ],
    },
    "verdad_alguna_vez": {
        "categoria": "verdad",
        "titulo": "¿Alguna vez...? (versión amable)",
        "prompts": [
            "¿Alguna vez fingiste que te gustaba un regalo que odiabas?",
            "¿Alguna vez te hiciste pasar por otra persona por chat?",
            "¿Alguna vez lloraste de la risa hasta que te dolió el estómago?",
            "¿Alguna vez practicaste una conversación antes de tenerla de verdad?",
            "¿Alguna vez te reíste en el peor momento posible?",
            "¿Alguna vez inventaste una excusa elaborada para no hacer algo?",
            "¿Alguna vez revisaste el perfil de alguien 50 veces en un día?",
            "¿Alguna vez te vestiste elegante solo para una videollamada?",
            "¿Alguna vez ensayaste un chiste antes de contarlo?",
            "¿Alguna vez fingiste que entendías algo en una conversación sin entender nada?",
        ],
    },
    "verdad_diario_abierto": {
        "categoria": "verdad",
        "titulo": "El diario abierto",
        "prompts": [
            "¿Cuál es tu recuerdo más vergonzoso de la primaria?",
            "¿Cuál fue tu peor berrinche de niño que recuerdes?",
            "¿Cuál era tu juego imaginario favorito de niño?",
            "¿Qué mentira de niño te creíste tú mismo por años?",
            "¿Cuál fue tu peor disfraz de niño?",
            "¿Qué programa de televisión de niño te marcó y hoy da un poco de risa?",
            "¿Cuál fue tu peor pelea de niño con un hermano o amigo?",
            "¿Qué querías ser de grande a los 8 años?",
            "¿Cuál fue tu primera mentira memorable de niño?",
            "¿Qué comida odiabas de niño y hoy amas (o viceversa)?",
        ],
    },
    "verdad_camara_indiscreta": {
        "categoria": "verdad",
        "titulo": "La cámara indiscreta",
        "prompts": [
            "Si alguien viera tu historial de redes sociales de esta semana, ¿qué pensaría de ti?",
            "Si alguien leyera tus últimos 5 mensajes enviados, ¿qué encontraría?",
            "Si alguien viera las fotos que tomaste hoy sin publicar, ¿qué habría?",
            "Si alguien escuchara lo que cantas cuando estás solo, ¿se sorprendería?",
            "Si alguien viera tu carrito de compras online abandonado, ¿qué encontraría?",
            "Si alguien viera cómo bailas cuando nadie te ve, ¿qué diría?",
            "Si alguien escuchara tu última nota de voz enviada, ¿qué encontraría?",
            "Si alguien viera cuántas veces abriste una sola app hoy, ¿se sorprendería?",
            "Si alguien viera tus búsquedas más recientes, ¿qué pensaría?",
            "Si alguien viera tu cuarto ahora mismo sin avisar, ¿qué diría?",
        ],
    },
    "verdad_o_verdad": {
        "categoria": "verdad",
        "titulo": "Verdad o verdad",
        "prompts": [
            "Elige: ¿cuál es tu mayor inseguridad, o cuál es tu mayor orgullo?",
            "Elige: ¿qué es lo que más te asusta del futuro, o qué es lo que más esperas de él?",
            "Elige: ¿qué cosa cambiarías de tu pasado, o qué cosa no cambiarías por nada?",
            "Elige: ¿cuál es tu mentira más repetida, o tu verdad más incómoda?",
            "Elige: ¿qué persona te ha decepcionado más, o qué persona te ha sorprendido más?",
            "Elige: ¿cuál es tu peor hábito, o tu mejor cualidad?",
            "Elige: ¿qué decisión te costó más tomar, o cuál tomaste sin pensar y salió bien?",
            "Elige: ¿de qué te arrepientes más, o de qué estás más orgulloso?",
            "Elige: ¿qué es lo que más ocultas, o qué es lo que más compartes con todos?",
            "Elige: ¿quién te conoce mejor, o quién crees que te malinterpreta más?",
        ],
    },
    "verdad_el_espejo": {
        "categoria": "verdad",
        "titulo": "El espejo",
        "prompts": [
            "¿Cómo crees que te describirían tus amigos en 3 palabras?",
            "¿Qué crees que la gente piensa de ti al conocerte, y es verdad?",
            "¿Qué cosa tuya crees que los demás notan más de lo que crees?",
            "¿Cuál crees que es tu mayor defecto visto desde afuera?",
            "¿Qué cumplido te han hecho que no terminas de creerte?",
            "¿Qué crees que la gente asume de ti que es totalmente falso?",
            "¿Cómo te describirías tú mismo en una sola palabra, honestamente?",
            "¿Qué parte de ti muestras menos a los demás?",
            "¿Qué crees que sorprendería más a alguien que te conoce poco?",
            "¿Con qué personaje de ficción te identificas más y por qué?",
        ],
    },
    "verdad_carta_sincera": {
        "categoria": "verdad",
        "titulo": "La carta sincera",
        "prompts": [
            "Si le escribieras una carta corta a tu yo del pasado, ¿qué le dirías?",
            "Si le escribieras una carta a alguien que ya no está en tu vida, ¿qué dirías?",
            "Si le escribieras una carta a tu mejor amigo, ¿qué le agradecerías?",
            "Si le escribieras una carta a alguien de este grupo, ¿qué dirías sin decir el nombre?",
            "Si le escribieras una carta a tu yo del futuro, ¿qué le preguntarías?",
            "Si le escribieras una carta a alguien que te lastimó, ¿qué dirías (sin rencor)?",
            "Si le escribieras una carta a un familiar, ¿qué le dirías que nunca le has dicho?",
            "Si le escribieras una carta a tu miedo más grande, ¿qué le dirías?",
            "Si le escribieras una carta a la versión más feliz de ti, ¿qué le preguntarías?",
            "Si le escribieras una carta a alguien que admiras, ¿qué le dirías?",
        ],
    },
    "verdad_detector_mentiras": {
        "categoria": "verdad",
        "titulo": "El detector de mentiras",
        "prompts": [
            "Di 3 cosas sobre ti: dos verdaderas y una falsa. Que el grupo adivine cuál miente.",
            "Di 3 lugares que has visitado: dos reales y uno inventado. Que adivinen cuál.",
            "Di 3 talentos que tienes: dos reales y uno inventado. Que adivinen cuál.",
            "Di 3 miedos tuyos: dos reales y uno inventado. Que adivinen cuál.",
            "Di 3 cosas vergonzosas que te han pasado: dos reales y una inventada. Que adivinen cuál.",
            "Di 3 comidas que odias: dos reales y una inventada. Que adivinen cuál.",
            "Di 3 cosas de tu infancia: dos reales y una inventada. Que adivinen cuál.",
            "Di 3 apodos que has tenido: dos reales y uno inventado. Que adivinen cuál.",
            "Di 3 datos sobre tu familia: dos reales y uno inventado. Que adivinen cuál.",
            "Di 3 sueños que has tenido: dos reales y uno inventado. Que adivinen cuál.",
        ],
    },
    "debate_indefendible": {
        "categoria": "debate",
        "titulo": "Defiende lo indefendible",
        "prompts": [
            "Defiende con argumentos serios: la piña sí va en la pizza.",
            "Defiende con argumentos serios: es mejor llegar tarde que temprano.",
            "Defiende con argumentos serios: los lunes son el mejor día de la semana.",
            "Defiende con argumentos serios: dormir la siesta debería ser obligatorio en el trabajo.",
            "Defiende con argumentos serios: el cereal es una sopa.",
            "Defiende con argumentos serios: los perritos calientes son sándwiches.",
            "Defiende con argumentos serios: es mejor ducharse de noche que de mañana.",
            "Defiende con argumentos serios: los memes son la forma más alta de arte.",
            "Defiende con argumentos serios: el silencio incómodo debería tener su propio santo patrono.",
            "Defiende con argumentos serios: es mejor no tener wifi un día a la semana.",
        ],
    },
    "debate_abogado_diablo": {
        "categoria": "debate",
        "titulo": "El abogado del diablo",
        "prompts": [
            "Di tu opinión sobre algo cotidiano y luego argumenta exactamente lo contrario.",
            "Defiende la postura opuesta a tu equipo o película favorita.",
            "Argumenta en contra de tu propia rutina diaria como si fuera pésima.",
            "Argumenta en contra de tu ciudad o país como si alguien te preguntara por qué no vivir ahí.",
            "Argumenta en contra de tu comida favorita como si fuera mala idea comerla.",
            "Argumenta en contra de tu forma de vestir habitual.",
            "Argumenta en contra de una costumbre que sigues sin cuestionar.",
            "Argumenta en contra de tu horario de dormir actual.",
            "Argumenta en contra de la red social que más usas.",
            "Argumenta en contra de tu propia opinión política o social más fuerte, con respeto.",
        ],
    },
    "debate_mesa_redonda": {
        "categoria": "debate",
        "titulo": "La mesa redonda",
        "prompts": [
            "Debate: ¿es peor llegar tarde o cancelar a última hora?",
            "Debate: ¿es mejor trabajar desde casa o en oficina?",
            "Debate: ¿las mascotas deberían dormir en la cama de sus dueños?",
            "Debate: ¿es más importante el talento o el esfuerzo?",
            "Debate: ¿los grupos de chat familiares son una bendición o una carga?",
            "Debate: ¿es mejor viajar planeado o improvisado?",
            "Debate: ¿deberían prohibirse los spoilers en redes sociales?",
            "Debate: ¿es peor un amigo impuntual o uno que cancela siempre?",
            "Debate: ¿es mejor comer solo o siempre acompañado?",
            "Debate: ¿el desayuno es realmente la comida más importante del día?",
        ],
    },
    "debate_congreso_improvisado": {
        "categoria": "debate",
        "titulo": "El congreso improvisado",
        "prompts": [
            "Propón y defiende una ley absurda para tu sociedad ideal: nadie puede usar el celular después de las 9pm.",
            "Propón y defiende una ley absurda: todos deben bailar 5 minutos antes de trabajar.",
            "Propón y defiende una ley absurda: está prohibido hablar antes del primer café del día.",
            "Propón y defiende una ley absurda: los viernes son obligatoriamente de pijama.",
            "Propón y defiende una ley absurda: nadie puede quejarse del clima más de una vez al día.",
            "Propón y defiende una ley absurda: toda reunión debe empezar con un chiste malo.",
            "Propón y defiende una ley absurda: está prohibido decir 'ya casi llego' si no es cierto.",
            "Propón y defiende una ley absurda: cada persona tiene derecho a una siesta pagada diaria.",
            "Propón y defiende una ley absurda: los grupos familiares de chat deben tener horario de silencio.",
            "Propón y defiende una ley absurda: nadie puede cancelar un plan sin proponer otro de inmediato.",
        ],
    },
    "debate_bien_o_mal": {
        "categoria": "debate",
        "titulo": "¿Bien o mal?",
        "prompts": [
            "¿Está bien mentir para no herir los sentimientos de alguien?",
            "¿Está bien leer los mensajes de alguien si te lo permite explícitamente?",
            "¿Está bien cancelar un plan si de verdad no tienes ganas de ir?",
            "¿Está bien copiar una idea si le das tu propio toque?",
            "¿Está bien no invitar a alguien a algo pequeño para evitar incomodidad?",
            "¿Está bien guardar rencor por algo pequeño durante mucho tiempo?",
            "¿Está bien decir 'estoy bien' cuando no lo estás, para no preocupar a otros?",
            "¿Está bien priorizar tu descanso sobre ayudar a un amigo en un mal momento?",
            "¿Está bien terminar una amistad sin dar explicaciones?",
            "¿Está bien exagerar una historia para hacerla más entretenida?",
        ],
    },
    "debate_juicio_rapido": {
        "categoria": "debate",
        "titulo": "El juicio rápido",
        "prompts": [
            "Caso: alguien llega tarde siempre pero avisa con tiempo. Da tu veredicto.",
            "Caso: alguien cancela un plan por cansancio pero luego publica que salió con otros. Da tu veredicto.",
            "Caso: alguien contesta los mensajes días después sin explicación. Da tu veredicto.",
            "Caso: alguien se come la última porción sin preguntar. Da tu veredicto.",
            "Caso: alguien usa el celular todo el tiempo en una reunión. Da tu veredicto.",
            "Caso: alguien cuenta un secreto ajeno 'sin querer'. Da tu veredicto.",
            "Caso: alguien no devuelve algo prestado hace meses. Da tu veredicto.",
            "Caso: alguien deja en visto un mensaje importante por días. Da tu veredicto.",
            "Caso: alguien organiza un plan y luego no llega. Da tu veredicto.",
            "Caso: alguien copia el estilo de otro amigo sin admitirlo. Da tu veredicto.",
        ],
    },
    "debate_balanza_valores": {
        "categoria": "debate",
        "titulo": "La balanza de valores",
        "prompts": [
            "Ordena del más al menos importante: honestidad, lealtad, puntualidad. Defiende el orden.",
            "Ordena del más al menos importante: ambición, humildad, generosidad. Defiende el orden.",
            "Ordena del más al menos importante: libertad, seguridad, comodidad. Defiende el orden.",
            "Ordena del más al menos importante: familia, amigos, pareja. Defiende el orden (con respeto).",
            "Ordena del más al menos importante: dinero, tiempo, salud. Defiende el orden.",
            "Ordena del más al menos importante: valentía, paciencia, sinceridad. Defiende el orden.",
            "Ordena del más al menos importante: éxito, tranquilidad, reconocimiento. Defiende el orden.",
            "Ordena del más al menos importante: fe, razón, tradición. Defiende el orden.",
            "Ordena del más al menos importante: independencia, comunidad, disciplina. Defiende el orden.",
            "Ordena del más al menos importante: gratitud, ambición, paciencia. Defiende el orden.",
        ],
    },
    "debate_gustos": {
        "categoria": "debate",
        "titulo": "El debate de los gustos",
        "prompts": [
            "Defiende por qué tu película favorita es objetivamente la mejor.",
            "Defiende por qué tu comida favorita le gana a cualquier otra.",
            "Defiende por qué tu serie favorita merece más reconocimiento.",
            "Defiende por qué tu género musical favorito es el más completo.",
            "Defiende por qué tu ciudad o país es el mejor lugar para vivir.",
            "Defiende por qué tu equipo o deporte favorito es el más entretenido.",
            "Defiende por qué tu libro favorito debería ser lectura obligatoria.",
            "Defiende por qué tu época favorita (década, era) fue la mejor.",
            "Defiende por qué tu forma de vacacionar es la ideal.",
            "Defiende por qué tu mascota (o la que quieres tener) es el mejor animal.",
        ],
    },
    "debate_cambia_mi_mente": {
        "categoria": "debate",
        "titulo": "Cambia mi mente",
        "prompts": [
            "En 30 segundos, argumenta: las redes sociales hacen más bien que mal.",
            "En 30 segundos, argumenta: es mejor vivir sin planes fijos.",
            "En 30 segundos, argumenta: el trabajo en equipo siempre es mejor que trabajar solo.",
            "En 30 segundos, argumenta: los errores son más valiosos que los aciertos.",
            "En 30 segundos, argumenta: es mejor decir siempre la verdad, aunque incomode.",
            "En 30 segundos, argumenta: el descanso es más importante que la productividad.",
            "En 30 segundos, argumenta: es mejor tener pocas metas grandes que muchas pequeñas.",
            "En 30 segundos, argumenta: la tecnología nos ha hecho más pacientes, no menos.",
            "En 30 segundos, argumenta: es mejor pedir perdón que pedir permiso.",
            "En 30 segundos, argumenta: reírse de uno mismo es la mejor cualidad que se puede tener.",
        ],
    },
    "debate_panel_expertos": {
        "categoria": "debate",
        "titulo": "El panel de expertos",
        "prompts": [
            "Finge ser experto en 'el arte de procrastinar' y da tu opinión con seguridad.",
            "Finge ser experto en 'cómo fingir que entendiste un chiste' y da tu opinión con seguridad.",
            "Finge ser experto en 'la ciencia de la siesta perfecta' y da tu opinión con seguridad.",
            "Finge ser experto en 'la etiqueta de los grupos de chat' y da tu opinión con seguridad.",
            "Finge ser experto en 'cómo sobrevivir un lunes' y da tu opinión con seguridad.",
            "Finge ser experto en 'el arte de cancelar planes' y da tu opinión con seguridad.",
            "Finge ser experto en 'la psicología de la última porción de comida' y da tu opinión con seguridad.",
            "Finge ser experto en 'cómo elegir qué ver en streaming' y da tu opinión con seguridad.",
            "Finge ser experto en 'el manejo de las notificaciones del celular' y da tu opinión con seguridad.",
            "Finge ser experto en 'la ciencia de decir mentiras piadosas' y da tu opinión con seguridad.",
        ],
    },
    "creatividad_historia_cadena": {
        "categoria": "creatividad",
        "titulo": "La historia en cadena",
        "prompts": [
            "Empieza una historia con: 'Todo empezó cuando encontré una llave que no abría ninguna puerta de mi casa...'",
            "Empieza una historia con: 'Nunca debí aceptar cuidar esa mascota por un fin de semana...'",
            "Empieza una historia con: 'El mensaje llegó a las 3 de la mañana y decía solo una palabra...'",
            "Empieza una historia con: 'Cuando abrí la puerta equivocada del edificio, no esperaba encontrar...'",
            "Empieza una historia con: 'Todos en el pueblo sabían el secreto, menos yo...'",
            "Empieza una historia con: 'La receta decía un ingrediente que nadie en la casa reconocía...'",
            "Empieza una historia con: 'El avión aterrizó en un aeropuerto que no aparecía en ningún mapa...'",
            "Empieza una historia con: 'Mi abuela me dejó una caja con instrucciones de abrirla solo hoy...'",
            "Empieza una historia con: 'El perro del vecino apareció con una nota amarrada al collar...'",
            "Empieza una historia con: 'Todo cambió el día que confundí dos frascos en la cocina...'",
        ],
    },
    "creatividad_micro_cuento": {
        "categoria": "creatividad",
        "titulo": "El micro-cuento",
        "prompts": [
            "Cuenta una historia completa (inicio, nudo, final) en 30 segundos sobre: un tesoro perdido.",
            "Cuenta una historia completa en 30 segundos sobre: una visita inesperada.",
            "Cuenta una historia completa en 30 segundos sobre: un objeto que cobra vida de noche.",
            "Cuenta una historia completa en 30 segundos sobre: un malentendido en una fiesta.",
            "Cuenta una historia completa en 30 segundos sobre: un viaje que sale mal desde el inicio.",
            "Cuenta una historia completa en 30 segundos sobre: una carta que llega 20 años tarde.",
            "Cuenta una historia completa en 30 segundos sobre: un animal que escapa de casa.",
            "Cuenta una historia completa en 30 segundos sobre: un plan perfecto que se arruina.",
            "Cuenta una historia completa en 30 segundos sobre: un reencuentro inesperado.",
            "Cuenta una historia completa en 30 segundos sobre: una promesa que cuesta cumplir.",
        ],
    },
    "creatividad_personaje_sorpresa": {
        "categoria": "creatividad",
        "titulo": "El personaje sorpresa",
        "prompts": [
            "Improvisa como si fueras un mesero muy dramático explicando el menú del día.",
            "Improvisa como si fueras un detective investigando quién se comió la última galleta.",
            "Improvisa como si fueras un presentador de noticias anunciando algo trivial como si fuera urgente.",
            "Improvisa como si fueras un vendedor intentando venderle algo inútil al grupo.",
            "Improvisa como si fueras un guía turístico mostrando tu propia casa como una atracción.",
            "Improvisa como si fueras un entrenador motivacional para una tarea aburrida (lavar platos).",
            "Improvisa como si fueras un comentarista deportivo narrando algo cotidiano.",
            "Improvisa como si fueras un mayordomo muy formal anunciando la llegada de alguien del grupo.",
            "Improvisa como si fueras un científico explicando por qué el café es indispensable.",
            "Improvisa como si fueras un rey o reina dando un discurso sobre las tareas del hogar.",
        ],
    },
    "creatividad_entrevista_imaginaria": {
        "categoria": "creatividad",
        "titulo": "La entrevista imaginaria",
        "prompts": [
            "Responde como si fueras una celebridad famosa a la que le preguntan su secreto del éxito.",
            "Responde como si fueras un explorador que acaba de descubrir algo increíble.",
            "Responde como si fueras un chef reconocido explicando tu plato más famoso (inventado).",
            "Responde como si fueras un astronauta contando cómo es la vida en el espacio.",
            "Responde como si fueras un personaje histórico dando su opinión sobre la vida moderna.",
            "Responde como si fueras el ganador de un premio inventado agradeciendo a todos.",
            "Responde como si fueras un inventor presentando tu creación más rara.",
            "Responde como si fueras un músico famoso hablando de tu próxima gira.",
            "Responde como si fueras un escritor hablando de tu libro más controvertido (inventado).",
            "Responde como si fueras un atleta olímpico contando tu rutina de entrenamiento (exagerada).",
        ],
    },
    "creatividad_guion_improvisado": {
        "categoria": "creatividad",
        "titulo": "El guion improvisado",
        "prompts": [
            "Recrea una escena corta: dos vecinos discutiendo por el ruido de una fiesta.",
            "Recrea una escena corta: una entrevista de trabajo que va mal desde el saludo.",
            "Recrea una escena corta: alguien devolviendo un producto con una excusa absurda.",
            "Recrea una escena corta: un cliente muy exigente en un restaurante imaginario.",
            "Recrea una escena corta: dos amigos reencontrándose después de años.",
            "Recrea una escena corta: alguien tratando de explicar por qué llegó tarde, de forma exagerada.",
            "Recrea una escena corta: una propuesta de negocio absurda a un inversionista.",
            "Recrea una escena corta: un profesor tratando de captar la atención de una clase aburrida.",
            "Recrea una escena corta: alguien negociando el precio de algo que no está en venta.",
            "Recrea una escena corta: una despedida dramática y exagerada en un aeropuerto.",
        ],
    },
    "creatividad_cuentacuentos": {
        "categoria": "creatividad",
        "titulo": "El cuentacuentos",
        "prompts": [
            "Inventa un final alternativo para Caperucita Roja.",
            "Inventa un final alternativo para Los Tres Cerditos.",
            "Inventa un final alternativo para Blancanieves.",
            "Inventa un final alternativo para Cenicienta.",
            "Inventa un final alternativo para El Patito Feo.",
            "Inventa un final alternativo para Hansel y Gretel.",
            "Inventa un final alternativo para La Bella Durmiente.",
            "Inventa un final alternativo para El Flautista de Hamelín.",
            "Inventa un final alternativo para Pinocho.",
            "Inventa un final alternativo para La Cigarra y la Hormiga.",
        ],
    },
    "creatividad_receta_imposible": {
        "categoria": "creatividad",
        "titulo": "La receta imposible",
        "prompts": [
            "Inventa una receta con: chocolate, cebolla y helado.",
            "Inventa una receta con: café, queso y fresas.",
            "Inventa una receta con: arroz, miel y aguacate.",
            "Inventa una receta con: pasta, mango y salsa picante.",
            "Inventa una receta con: pollo, chocolate y coco.",
            "Inventa una receta con: banana, ajo y pan.",
            "Inventa una receta con: huevo, piña y menta.",
            "Inventa una receta con: papa, canela y limón.",
            "Inventa una receta con: yogur, aceituna y miel.",
            "Inventa una receta con: pescado, sandía y albahaca.",
        ],
    },
    "creatividad_titular_falso": {
        "categoria": "creatividad",
        "titulo": "El titular falso",
        "prompts": [
            "Inventa una noticia divertida usando las palabras: gato, alcalde, helado.",
            "Inventa una noticia divertida usando las palabras: robot, panadería, lluvia.",
            "Inventa una noticia divertida usando las palabras: abuela, dron, torneo.",
            "Inventa una noticia divertida usando las palabras: bicicleta, presidente, pastel.",
            "Inventa una noticia divertida usando las palabras: perro, banco, karaoke.",
            "Inventa una noticia divertida usando las palabras: escuela, cometa, pizza.",
            "Inventa una noticia divertida usando las palabras: playa, científico, gallina.",
            "Inventa una noticia divertida usando las palabras: taxi, fantasma, examen.",
            "Inventa una noticia divertida usando las palabras: jardín, celebridad, paraguas.",
            "Inventa una noticia divertida usando las palabras: oficina, dinosaurio, boda.",
        ],
    },
    "creatividad_monologo_minuto": {
        "categoria": "creatividad",
        "titulo": "El monólogo de un minuto",
        "prompts": [
            "Habla sin parar por un minuto sobre: por qué los lunes tienen mala fama.",
            "Habla sin parar por un minuto sobre: la importancia de la siesta.",
            "Habla sin parar por un minuto sobre: por qué el tráfico saca lo peor de las personas.",
            "Habla sin parar por un minuto sobre: el arte perdido de las cartas escritas a mano.",
            "Habla sin parar por un minuto sobre: por qué los memes son el nuevo folclore.",
            "Habla sin parar por un minuto sobre: la ciencia secreta de encontrar estacionamiento.",
            "Habla sin parar por un minuto sobre: por qué el café es más que una bebida.",
            "Habla sin parar por un minuto sobre: la filosofía de dejar cosas para después.",
            "Habla sin parar por un minuto sobre: por qué las mascotas son mejores jefes que los humanos.",
            "Habla sin parar por un minuto sobre: el misterio de los calcetines perdidos en el lavado.",
        ],
    },
    "creatividad_objeto_misterioso": {
        "categoria": "creatividad",
        "titulo": "El objeto misterioso",
        "prompts": [
            "Inventa una historia sobre el origen misterioso de: un paraguas roto.",
            "Inventa una historia sobre el origen misterioso de: una llave sin puerta conocida.",
            "Inventa una historia sobre el origen misterioso de: un reloj detenido en una hora exacta.",
            "Inventa una historia sobre el origen misterioso de: una foto sin nadie identificado.",
            "Inventa una historia sobre el origen misterioso de: una carta sin firma.",
            "Inventa una historia sobre el origen misterioso de: un botón de un abrigo desconocido.",
            "Inventa una historia sobre el origen misterioso de: una moneda de un país que no existe.",
            "Inventa una historia sobre el origen misterioso de: un mapa dibujado a mano sin nombres.",
            "Inventa una historia sobre el origen misterioso de: una caja musical que nadie recuerda comprar.",
            "Inventa una historia sobre el origen misterioso de: un anillo encontrado en un libro viejo.",
        ],
    },
    "conocerse_preguntas_del_alma": {
        "categoria": "conocerse",
        "titulo": "Preguntas del alma",
        "prompts": [
            "¿Qué sueño tienes que no le has contado a casi nadie?",
            "¿Qué es lo que más te asusta de crecer o envejecer?",
            "¿Qué meta tienes para este año que aún no le has contado a nadie?",
            "¿Qué es lo que más valoras en una amistad?",
            "¿Qué te hace sentir realmente en paz?",
            "¿Qué parte de ti ha cambiado más en los últimos años?",
            "¿Qué es lo que más te cuesta perdonar, en general?",
            "¿Qué necesitas escuchar más seguido de las personas que quieres?",
            "¿Qué es lo que te haría sentir que tu vida fue significativa?",
            "¿Qué es lo que más te gustaría que la gente entendiera de ti?",
        ],
    },
    "conocerse_linea_tiempo": {
        "categoria": "conocerse",
        "titulo": "La línea de tiempo",
        "prompts": [
            "¿Cuál fue el momento en que sentiste que 'creciste' de golpe?",
            "¿Cuál ha sido la decisión más importante que has tomado hasta ahora?",
            "¿Cuál fue el momento más feliz de tu adolescencia?",
            "¿Cuál ha sido el reto más grande que has superado?",
            "¿Cuál fue el momento en que más orgulloso te sentiste de ti mismo?",
            "¿Cuál fue un punto de quiebre que cambió tu forma de ver la vida?",
            "¿Cuál fue la etapa más difícil que has vivido hasta ahora?",
            "¿Cuál fue el momento en que sentiste más apoyo de tu familia o amigos?",
            "¿Cuál ha sido tu mayor logro personal, aunque parezca pequeño?",
            "¿Qué momento de tu vida repetirías exactamente igual?",
        ],
    },
    "conocerse_mapa_gratitud": {
        "categoria": "conocerse",
        "titulo": "El mapa de gratitud",
        "prompts": [
            "Nombra algo pequeño de hoy por lo que estás agradecido.",
            "Nombra a una persona por la que estás agradecido y por qué.",
            "Nombra algo de tu cuerpo o salud por lo que estás agradecido.",
            "Nombra un lugar por el que estás agradecido de haber conocido.",
            "Nombra una lección difícil por la que, viéndolo bien, estás agradecido.",
            "Nombra algo de tu familia por lo que estás agradecido.",
            "Nombra un talento tuyo por el que estás agradecido.",
            "Nombra algo de este grupo de amigos por lo que estás agradecido.",
            "Nombra un recuerdo por el que estás agradecido de tener.",
            "Nombra algo simple del día a día que sueles dar por sentado.",
        ],
    },
    "conocerse_metas_secretas": {
        "categoria": "conocerse",
        "titulo": "Las metas secretas",
        "prompts": [
            "Comparte una meta personal que no sueles contar.",
            "Comparte un sueño 'poco realista' que aún no abandonas del todo.",
            "Comparte una meta que pospones por miedo, no por falta de tiempo.",
            "Comparte algo que quieres aprender antes de cumplir 40 (o antes de cierta edad).",
            "Comparte una meta que ya lograste en secreto y nunca celebraste con nadie.",
            "Comparte un lugar donde te gustaría vivir algún día.",
            "Comparte una meta relacionada con tu familia o relaciones.",
            "Comparte una meta pequeña que quieres lograr este mes.",
            "Comparte una meta que cambiaste con los años y por qué.",
            "Comparte qué meta te gustaría lograr junto a alguien de este grupo.",
        ],
    },
    "conocerse_recuerdo_favorito": {
        "categoria": "conocerse",
        "titulo": "El recuerdo favorito",
        "prompts": [
            "Cuenta un recuerdo feliz relacionado con la comida.",
            "Cuenta un recuerdo feliz relacionado con un viaje.",
            "Cuenta un recuerdo feliz relacionado con tu familia.",
            "Cuenta un recuerdo feliz relacionado con la escuela o universidad.",
            "Cuenta un recuerdo feliz relacionado con una celebración.",
            "Cuenta un recuerdo feliz relacionado con un amigo de la infancia.",
            "Cuenta un recuerdo feliz relacionado con un logro personal.",
            "Cuenta un recuerdo feliz relacionado con una mascota.",
            "Cuenta un recuerdo feliz relacionado con un lugar al aire libre.",
            "Cuenta un recuerdo feliz relacionado con una canción o música.",
        ],
    },
    "conocerse_carta_futuro": {
        "categoria": "conocerse",
        "titulo": "La carta al futuro",
        "prompts": [
            "¿Qué le dirías a tu yo de dentro de 10 años?",
            "¿Qué le preguntarías a tu yo de dentro de 10 años?",
            "¿Qué esperas que tu yo futuro haya logrado?",
            "¿Qué esperas que tu yo futuro no haya cambiado de ti?",
            "¿Qué consejo crees que tu yo futuro te daría hoy?",
            "¿Qué le advertirías a tu yo futuro que no repita?",
            "¿Qué te gustaría que tu yo futuro recordara de este momento exacto?",
            "¿Qué esperas estar haciendo dentro de 10 años un día cualquiera?",
            "¿Qué relación esperas que tu yo futuro siga cuidando?",
            "¿Qué miedo de hoy esperas que tu yo futuro ya haya superado?",
        ],
    },
    "conocerse_valor_importante": {
        "categoria": "conocerse",
        "titulo": "El valor más importante",
        "prompts": [
            "¿Qué valor crees que más te define y por qué?",
            "¿Qué valor te gustaría fortalecer más este año?",
            "¿Qué valor aprendiste de tu familia que más aprecias?",
            "¿Qué valor consideras innegociable en una amistad?",
            "¿Qué valor te cuesta más practicar en el día a día?",
            "¿Qué valor admiras más en otras personas?",
            "¿Qué valor te gustaría transmitirle a alguien más joven que tú?",
            "¿Qué valor crees que la sociedad actual necesita más?",
            "¿Qué valor asocias más con tu fe o tus creencias?",
            "¿Qué valor te ha ayudado a superar un momento difícil?",
        ],
    },
    "conocerse_lecciones_vida": {
        "categoria": "conocerse",
        "titulo": "Las lecciones de vida",
        "prompts": [
            "Comparte una lección que aprendiste de un fracaso.",
            "Comparte una lección que aprendiste de una amistad que terminó.",
            "Comparte una lección que aprendiste de tus padres o cuidadores.",
            "Comparte una lección que aprendiste viajando o conociendo gente nueva.",
            "Comparte una lección que aprendiste de un trabajo o estudio difícil.",
            "Comparte una lección que aprendiste demasiado tarde.",
            "Comparte una lección que te enseñó una mascota.",
            "Comparte una lección que aprendiste de una pérdida o despedida.",
            "Comparte una lección que aprendiste de un error que cometiste en público.",
            "Comparte una lección que te gustaría que otros aprendieran más rápido que tú.",
        ],
    },
    "conocerse_circulo_confianza": {
        "categoria": "conocerse",
        "titulo": "El círculo de confianza",
        "prompts": [
            "¿Qué es lo que más valoras de la amistad de las personas aquí presentes?",
            "¿Qué te hace confiar en alguien rápidamente?",
            "¿Qué te hace perder la confianza en alguien?",
            "¿Cómo prefieres que te apoyen cuando pasas por un mal momento?",
            "¿Qué tipo de amigo eres tú: el que escucha, el que aconseja, el que hace reír?",
            "¿Qué has aprendido de las amistades que ya no tienes?",
            "¿Qué esperas de una amistad a largo plazo?",
            "¿Cómo demuestras cariño a tus amigos, aunque no lo digas directamente?",
            "¿Qué amistad te ha marcado más en la vida?",
            "¿Qué le dirías a un amigo que está pasando un mal momento ahora mismo?",
        ],
    },
    "conocerse_tres_palabras": {
        "categoria": "conocerse",
        "titulo": "Mi historia en 3 palabras",
        "prompts": [
            "Resume tu infancia en 3 palabras.",
            "Resume tu adolescencia en 3 palabras.",
            "Resume tu año actual en 3 palabras.",
            "Resume tu familia en 3 palabras.",
            "Resume tu personalidad en 3 palabras.",
            "Resume tu relación con la comida en 3 palabras.",
            "Resume tu forma de amar en 3 palabras.",
            "Resume tu relación con el trabajo o estudio en 3 palabras.",
            "Resume tu sentido del humor en 3 palabras.",
            "Resume lo que esperas del futuro en 3 palabras.",
        ],
    },
    "ingenio_categorias": {
        "categoria": "ingenio",
        "titulo": "Categorías",
        "prompts": [
            "Nombra rápido 5 frutas antes de que se acabe el tiempo.",
            "Nombra rápido 5 países que empiecen con la misma letra.",
            "Nombra rápido 5 series o películas de superhéroes.",
            "Nombra rápido 5 cosas que encuentras en una cocina.",
            "Nombra rápido 5 animales que vivan en el agua.",
            "Nombra rápido 5 profesiones que empiecen con 'P'.",
            "Nombra rápido 5 colores que no sean primarios.",
            "Nombra rápido 5 instrumentos musicales.",
            "Nombra rápido 5 cosas que llevarías a un picnic.",
            "Nombra rápido 5 palabras relacionadas con la playa.",
        ],
    },
    "ingenio_palabra_encadenada": {
        "categoria": "ingenio",
        "titulo": "Palabra encadenada",
        "prompts": [
            "Empieza con la palabra 'sol': la siguiente debe iniciar con su última letra.",
            "Empieza con la palabra 'luna': la siguiente debe iniciar con su última letra.",
            "Empieza con la palabra 'árbol': la siguiente debe iniciar con su última letra.",
            "Empieza con la palabra 'mesa': la siguiente debe iniciar con su última letra.",
            "Empieza con la palabra 'río': la siguiente debe iniciar con su última letra.",
            "Empieza con la palabra 'pan': la siguiente debe iniciar con su última letra.",
            "Empieza con la palabra 'flor': la siguiente debe iniciar con su última letra.",
            "Empieza con la palabra 'nube': la siguiente debe iniciar con su última letra.",
            "Empieza con la palabra 'gato': la siguiente debe iniciar con su última letra.",
            "Empieza con la palabra 'reloj': la siguiente debe iniciar con su última letra.",
        ],
    },
    "ingenio_acrostico_expres": {
        "categoria": "ingenio",
        "titulo": "El acróstico exprés",
        "prompts": [
            "Crea una frase divertida usando las letras de la palabra AMOR.",
            "Crea una frase divertida usando las letras de la palabra FIESTA.",
            "Crea una frase divertida usando las letras de la palabra RISA.",
            "Crea una frase divertida usando las letras de la palabra SUEÑO.",
            "Crea una frase divertida usando las letras de la palabra VIAJE.",
            "Crea una frase divertida usando las letras de la palabra CASA.",
            "Crea una frase divertida usando las letras de la palabra PAZ.",
            "Crea una frase divertida usando las letras de la palabra LUZ.",
            "Crea una frase divertida usando las letras de la palabra FE.",
            "Crea una frase divertida usando las letras de la palabra HOGAR.",
        ],
    },
    "ingenio_rima_si_puedes": {
        "categoria": "ingenio",
        "titulo": "Rima si puedes",
        "prompts": [
            "Di una palabra que rime con 'amor'.",
            "Di una palabra que rime con 'corazón'.",
            "Di una palabra que rime con 'canción'.",
            "Di una palabra que rime con 'ventana'.",
            "Di una palabra que rime con 'camino'.",
            "Di una palabra que rime con 'estrella'.",
            "Di una palabra que rime con 'jardín'.",
            "Di una palabra que rime con 'montaña'.",
            "Di una palabra que rime con 'sonrisa'.",
            "Di una palabra que rime con 'silencio'.",
        ],
    },
    "ingenio_alfabeto_tematico": {
        "categoria": "ingenio",
        "titulo": "El alfabeto temático",
        "prompts": [
            "Nombra un animal por cada letra que puedas, empezando por la A.",
            "Nombra una comida por cada letra que puedas, empezando por la A.",
            "Nombra un país por cada letra que puedas, empezando por la A.",
            "Nombra un nombre propio por cada letra que puedas, empezando por la A.",
            "Nombra una profesión por cada letra que puedas, empezando por la A.",
            "Nombra un objeto de la casa por cada letra que puedas, empezando por la A.",
            "Nombra una película por cada letra que puedas, empezando por la A.",
            "Nombra un deporte por cada letra que puedas, empezando por la A.",
            "Nombra una ciudad por cada letra que puedas, empezando por la A.",
            "Nombra una palabra bonita por cada letra que puedas, empezando por la A.",
        ],
    },
    "ingenio_asociacion_libre": {
        "categoria": "ingenio",
        "titulo": "Asociación libre",
        "prompts": [
            "Di la primera palabra que se te ocurra al oír: 'verano'.",
            "Di la primera palabra que se te ocurra al oír: 'familia'.",
            "Di la primera palabra que se te ocurra al oír: 'miedo'.",
            "Di la primera palabra que se te ocurra al oír: 'libertad'.",
            "Di la primera palabra que se te ocurra al oír: 'hogar'.",
            "Di la primera palabra que se te ocurra al oír: 'música'.",
            "Di la primera palabra que se te ocurra al oír: 'domingo'.",
            "Di la primera palabra que se te ocurra al oír: 'infancia'.",
            "Di la primera palabra que se te ocurra al oír: 'viaje'.",
            "Di la primera palabra que se te ocurra al oír: 'esperanza'.",
        ],
    },
    "ingenio_acertijo_del_dia": {
        "categoria": "ingenio",
        "titulo": "El acertijo del día",
        "prompts": [
            "Adivina: cuanto más le quitas, más grande se hace. ¿Qué es?",
            "Adivina: tiene ciudades pero no casas, bosques pero no árboles, ríos pero no agua. ¿Qué es?",
            "Adivina: no tiene vida, pero puede morir. ¿Qué es?",
            "Adivina: mientras más seco está, más mojado parece. ¿Qué es?",
            "Adivina: entre más alto, menos pesa. ¿Qué es?",
            "Adivina: lo tienes pero lo compartes con otros sin quedarte sin él. ¿Qué es?",
            "Adivina: te lo dan, lo usas, pero nunca lo ves. ¿Qué es?",
            "Adivina: no tiene alas pero vuela, no tiene ojos pero llora. ¿Qué es?",
            "Adivina: cuanto más grande, menos se ve. ¿Qué es?",
            "Adivina: siempre viene pero nunca llega. ¿Qué es?",
        ],
    },
    "ingenio_contrarios_expres": {
        "categoria": "ingenio",
        "titulo": "Contrarios exprés",
        "prompts": [
            "Di el antónimo de 'feliz'.",
            "Di el antónimo de 'rápido'.",
            "Di el antónimo de 'grande'.",
            "Di el antónimo de 'valiente'.",
            "Di el antónimo de 'claro'.",
            "Di el antónimo de 'ordenado'.",
            "Di el antónimo de 'generoso'.",
            "Di el antónimo de 'fuerte'.",
            "Di el antónimo de 'cercano'.",
            "Di el antónimo de 'simple'.",
        ],
    },
    "ingenio_trabalenguas": {
        "categoria": "ingenio",
        "titulo": "El trabalenguas",
        "prompts": [
            "Repite 3 veces rápido: 'Tres tristes tigres tragaban trigo en un trigal'.",
            "Repite 3 veces rápido: 'El cielo está enladrillado, quién lo desenladrillará'.",
            "Repite 3 veces rápido: 'Pablito clavó un clavito en la calva de un calvito'.",
            "Repite 3 veces rápido: 'Como poco coco como, poco coco compro'.",
            "Repite 3 veces rápido: 'El perro de San Roque no tiene rabo'.",
            "Repite 3 veces rápido: 'Compré pocas copas, pocas copas compré'.",
            "Repite 3 veces rápido: 'Si Sansón no sazona su salsa con sal, la salsa de Sansón sin sal no sabe'.",
            "Repite 3 veces rápido: 'La bruja piruja prepara su brebaje'.",
            "Repite 3 veces rápido: 'Erre con erre cigarro, erre con erre barril'.",
            "Repite 3 veces rápido: 'Papá pone pan en la panera y la panera nunca queda vacía'.",
        ],
    },
    "ingenio_adivinanza": {
        "categoria": "ingenio",
        "titulo": "La adivinanza",
        "prompts": [
            "Adivina: blanca por dentro, verde por fuera, si quieres que te lo diga espera. ¿Qué es?",
            "Adivina: oro parece, plata no es. ¿Qué es?",
            "Adivina: agua pasa por mi casa, cate de mi corazón. ¿Qué es?",
            "Adivina: tengo hojas pero no soy árbol, tengo lomo pero no soy animal. ¿Qué es?",
            "Adivina: sube y baja pero no camina. ¿Qué es?",
            "Adivina: te la digo, te la digo, te la vuelvo a repetir, y si no me la adivinas, te la vuelvo a decir. ¿Qué es?",
            "Adivina: redonda como un plato, da la vuelta al mundo pero no se cae del techo. ¿Qué es?",
            "Adivina: tiene manos pero no aplaude. ¿Qué es?",
            "Adivina: cuantas más tienes, menos ves. ¿Qué es?",
            "Adivina: en un cuarto oscuro sin ninguna luz, alguien está cosiendo, ¿cómo se llama?",
        ],
    },
    "memoria_quien_dijo_que": {
        "categoria": "memoria",
        "titulo": "¿Quién dijo qué?",
        "prompts": [
            "Recuerden entre todos: ¿quién fue el último en contar un chiste en esta charla?",
            "Recuerden entre todos: ¿quién mencionó una comida primero hoy?",
            "Recuerden entre todos: ¿quién habló de un viaje o plan futuro más reciente?",
            "Recuerden entre todos: ¿quién se quejó del clima más recientemente?",
            "Recuerden entre todos: ¿quién mencionó una serie o película primero?",
            "Recuerden entre todos: ¿quién contó una anécdota vergonzosa más reciente?",
            "Recuerden entre todos: ¿quién fue el último en proponer un plan para salir?",
            "Recuerden entre todos: ¿quién mencionó a su familia más recientemente?",
            "Recuerden entre todos: ¿quién hizo la última pregunta random del grupo?",
            "Recuerden entre todos: ¿quién fue el último en cambiar de tema de conversación?",
        ],
    },
    "memoria_lista_que_crece": {
        "categoria": "memoria",
        "titulo": "La lista que crece",
        "prompts": [
            "Empiecen una lista de frutas: cada quien repite las anteriores y añade una nueva.",
            "Empiecen una lista de países: cada quien repite las anteriores y añade uno nuevo.",
            "Empiecen una lista de cosas que llevarían de viaje: repitan y añadan una nueva cada turno.",
            "Empiecen una lista de películas: cada quien repite las anteriores y añade una nueva.",
            "Empiecen una lista de animales: cada quien repite los anteriores y añade uno nuevo.",
            "Empiecen una lista de cosas de la nevera: repitan y añadan una nueva cada turno.",
            "Empiecen una lista de canciones: cada quien repite las anteriores y añade una nueva.",
            "Empiecen una lista de superhéroes: cada quien repite los anteriores y añade uno nuevo.",
            "Empiecen una lista de lugares de la ciudad: repitan y añadan uno nuevo cada turno.",
            "Empiecen una lista de nombres propios: cada quien repite los anteriores y añade uno nuevo.",
        ],
    },
    "memoria_detalle_escondido": {
        "categoria": "memoria",
        "titulo": "El detalle escondido",
        "prompts": [
            "Alguien cuenta una historia corta de 30 segundos; luego el grupo debe recordar 3 detalles exactos.",
            "Alguien describe su desayuno de hoy con detalle; el grupo debe repetirlo palabra por palabra después.",
            "Alguien cuenta un sueño reciente; el grupo debe recordar el orden exacto de los eventos.",
            "Alguien describe su cuarto sin mirarlo; el grupo hace preguntas para adivinar qué falta en la descripción.",
            "Alguien cuenta su ruta de hoy (a dónde fue); el grupo debe repetir la secuencia exacta.",
            "Alguien nombra 5 objetos que tiene cerca; el grupo debe recordarlos en el mismo orden.",
            "Alguien cuenta una anécdota con 3 nombres propios; el grupo debe recordar los 3 nombres.",
            "Alguien describe un plato de comida con 4 ingredientes; el grupo debe recordarlos todos.",
            "Alguien cuenta los planes de su semana; el grupo debe repetir el orden de los días.",
            "Alguien menciona 3 lugares que visitó este año; el grupo debe recordarlos en orden.",
        ],
    },
    "memoria_de_grupo": {
        "categoria": "memoria",
        "titulo": "Memoria de grupo",
        "prompts": [
            "¿Alguien recuerda el dato curioso que se compartió antes en esta misma sesión de juegos?",
            "¿Alguien recuerda qué comida mencionó alguien del grupo hoy?",
            "¿Alguien recuerda una meta secreta que alguien compartió hoy?",
            "¿Alguien recuerda un miedo que alguien mencionó en una ronda anterior?",
            "¿Alguien recuerda qué película o serie defendió alguien en el debate de hoy?",
            "¿Alguien recuerda un recuerdo feliz que alguien contó hoy?",
            "¿Alguien recuerda una confesión curiosa que alguien compartió hoy?",
            "¿Alguien recuerda qué dilema eligió alguien del grupo hace un rato?",
            "¿Alguien recuerda un apodo vergonzoso que alguien mencionó hoy?",
            "¿Alguien recuerda la historia inventada que alguien contó en la ronda de creatividad?",
        ],
    },
    "memoria_resumen_exacto": {
        "categoria": "memoria",
        "titulo": "El resumen exacto",
        "prompts": [
            "Resuman en una sola frase de qué trató la última ronda de este juego.",
            "Resuman en una sola frase el chiste o anécdota más reciente que contaron.",
            "Resuman en una sola frase el debate más reciente del grupo.",
            "Resuman en una sola frase la historia inventada más reciente.",
            "Resuman en una sola frase lo más gracioso que pasó en esta sesión de juegos.",
            "Resuman en una sola frase el último dilema que discutieron.",
            "Resuman en una sola frase la última confesión compartida.",
            "Resuman en una sola frase la última meta o sueño compartido.",
            "Resuman en una sola frase la última pregunta random que se hizo.",
            "Resuman en una sola frase lo que más se rieron hoy jugando.",
        ],
    },
    "memoria_secuencia": {
        "categoria": "memoria",
        "titulo": "La secuencia",
        "prompts": [
            "Repitan esta secuencia en orden: manzana, silla, luna, zapato.",
            "Repitan esta secuencia en orden: 7, azul, gato, lunes.",
            "Repitan esta secuencia en orden: sol, libro, tres, ventana.",
            "Repitan esta secuencia en orden: café, martes, verde, puerta.",
            "Repitan esta secuencia en orden: pan, doce, montaña, reloj.",
            "Repitan esta secuencia en orden: flor, rojo, cinco, tren.",
            "Repitan esta secuencia en orden: mar, nueve, silla, estrella.",
            "Repitan esta secuencia en orden: nube, dos, camino, vaso.",
            "Repitan esta secuencia en orden: fuego, ocho, jardín, taza.",
            "Repitan esta secuencia en orden: río, seis, espejo, cuchara.",
        ],
    },
    "memoria_que_falta": {
        "categoria": "memoria",
        "titulo": "¿Qué falta?",
        "prompts": [
            "Lista: manzana, pera, uva, mango. Ahora digan la misma lista de memoria... ¿falta alguna?",
            "Lista: perro, gato, loro, pez. Repítanla de memoria... ¿la dijeron completa?",
            "Lista: lunes, martes, jueves, viernes. ¿Qué día falta en esta secuencia?",
            "Lista: rojo, azul, amarillo. ¿Qué color primario falta?",
            "Lista: cabeza, brazo, pierna. ¿Qué parte del cuerpo obvia falta?",
            "Lista: enero, febrero, abril. ¿Qué mes falta entre los mencionados?",
            "Lista: taza, plato, cuchara. ¿Qué utensilio de mesa falta?",
            "Lista: uno, dos, cuatro, cinco. ¿Qué número falta?",
            "Lista: primavera, verano, invierno. ¿Qué estación falta?",
            "Lista: do, re, mi, sol. ¿Qué nota musical falta?",
        ],
    },
    "memoria_el_eco": {
        "categoria": "memoria",
        "titulo": "El eco",
        "prompts": [
            "Repite exactamente la última frase que dijo la persona antes que tú, luego da tu respuesta.",
            "Repite exactamente las últimas 5 palabras dichas en el grupo antes de hablar.",
            "Repite el nombre de la última persona que habló antes de responder tú.",
            "Repite el último chiste contado, palabra por palabra, antes de continuar.",
            "Repite la última pregunta hecha en el grupo, exactamente como se dijo.",
            "Repite el último dato curioso compartido antes de dar tu opinión.",
            "Repite la última cosa graciosa que se dijo, imitando el tono si puedes.",
            "Repite la última meta o sueño compartido antes de compartir el tuyo.",
            "Repite el último 'esto o aquello' que se discutió antes de proponer uno nuevo.",
            "Repite la última frase completa dicha en el chat antes de tu turno.",
        ],
    },
    "memoria_mapa_mental": {
        "categoria": "memoria",
        "titulo": "El mapa mental",
        "prompts": [
            "Conecta tu respuesta con algo que ya se mencionó antes en esta sesión de juegos.",
            "Menciona algo que te recuerde a una historia contada anteriormente hoy.",
            "Conecta tu comida favorita con un recuerdo ya compartido en el grupo.",
            "Menciona cómo se relaciona tu meta secreta con algo que dijo otra persona hoy.",
            "Conecta un miedo tuyo con algo que ya se discutió en el juego de debate.",
            "Menciona qué tiene en común tu recuerdo favorito con el de otra persona del grupo.",
            "Conecta tu último dilema elegido con una de tus metas mencionadas hoy.",
            "Menciona cómo se relaciona la última historia inventada con la vida real de alguien.",
            "Conecta el último dato curioso compartido con algo de tu propia vida.",
            "Menciona qué tienen en común dos respuestas distintas dadas hoy en el grupo.",
        ],
    },
    "memoria_fotografica": {
        "categoria": "memoria",
        "titulo": "La memoria fotográfica",
        "prompts": [
            "Describan de memoria lo que alguien llevaba puesto la última vez que se vieron en persona.",
            "Describan de memoria cómo era el lugar de la última reunión del grupo.",
            "Describan de memoria el postre o plato principal de la última comida juntos.",
            "Describan de memoria la última foto grupal que se tomaron.",
            "Describan de memoria el clima del último día que salieron juntos.",
            "Describan de memoria la decoración de la última fiesta a la que fueron juntos.",
            "Describan de memoria qué canción sonaba la última vez que estuvieron juntos escuchando música.",
            "Describan de memoria el regalo más reciente que alguien del grupo recibió.",
            "Describan de memoria el último chiste interno que tiene el grupo.",
            "Describan de memoria el último lugar nuevo que visitaron juntos.",
        ],
    },
    "fe_preguntas_de_fe": {
        "categoria": "fe",
        "titulo": "Preguntas de fe",
        "prompts": [
            "¿Qué momento sientes que Dios estuvo más presente en tu vida?",
            "¿Qué virtud te gustaría que Dios te ayudara a fortalecer?",
            "¿Cómo describirías tu relación con la fe en una sola frase?",
            "¿Qué canción o himno te conecta más con tu fe?",
            "¿Qué historia bíblica te ha marcado más y por qué?",
            "¿Qué te ayuda a sentirte en paz espiritualmente?",
            "¿Qué le pedirías a Dios si supieras que la respuesta es sí?",
            "¿Qué persona te ha mostrado la fe con el ejemplo?",
            "¿Qué duda de fe te gustaría resolver algún día?",
            "¿Cómo describirías la esperanza con tus propias palabras?",
        ],
    },
    "fe_versiculo_sorpresa": {
        "categoria": "fe",
        "titulo": "El versículo sorpresa",
        "prompts": [
            "Reflexiona: 'Todo lo puedo en Cristo que me fortalece' (Filipenses 4:13). ¿Qué te dice hoy?",
            "Reflexiona: 'El amor es paciente, es bondadoso' (1 Corintios 13:4). ¿A quién te recuerda?",
            "Reflexiona: 'No temas, porque yo estoy contigo' (Isaías 41:10). ¿Cuándo lo necesitaste más?",
            "Reflexiona: 'Encomienda a Jehová tu camino' (Salmos 37:5). ¿Qué camino le encomendarías hoy?",
            "Reflexiona: 'Dad gracias en todo' (1 Tesalonicenses 5:18). ¿Por qué darías gracias hoy?",
            "Reflexiona: 'El que siembra escasamente, escasamente segará' (2 Corintios 9:6). ¿Qué siembras últimamente?",
            "Reflexiona: 'Bienaventurados los pacificadores' (Mateo 5:9). ¿Cuándo has sido pacificador?",
            "Reflexiona: 'Todo tiene su tiempo' (Eclesiastés 3:1). ¿En qué 'tiempo' sientes que estás ahora?",
            "Reflexiona: 'El gozo del Señor es vuestra fuerza' (Nehemías 8:10). ¿Qué te da gozo hoy?",
            "Reflexiona: 'Amarás a tu prójimo como a ti mismo' (Marcos 12:31). ¿Cómo lo vives esta semana?",
        ],
    },
    "fe_gratitud_diaria": {
        "categoria": "fe",
        "titulo": "Gratitud diaria",
        "prompts": [
            "¿Por qué le darías gracias a Dios hoy, aunque sea algo pequeño?",
            "¿Qué bendición inesperada has recibido esta semana?",
            "¿Por qué persona de tu vida le darías gracias a Dios hoy?",
            "¿Qué dificultad superada agradeces hoy con el tiempo?",
            "¿Qué parte de tu salud o cuerpo agradeces hoy?",
            "¿Qué provisión (comida, techo, trabajo) agradeces hoy sin darla por sentada?",
            "¿Qué aprendizaje espiritual agradeces de este último año?",
            "¿Qué momento de paz agradeces haber vivido recientemente?",
            "¿Qué relación familiar agradeces hoy?",
            "¿Qué segunda oportunidad agradeces haber recibido en tu vida?",
        ],
    },
    "fe_parabola_moderna": {
        "categoria": "fe",
        "titulo": "La parábola moderna",
        "prompts": [
            "Reinterpreta la parábola del Hijo Pródigo en un contexto de hoy (familia, celular, redes).",
            "Reinterpreta la parábola del Buen Samaritano con una situación cotidiana actual.",
            "Reinterpreta la parábola de los Talentos pensando en tus propias habilidades hoy.",
            "Reinterpreta la parábola de la Oveja Perdida con una amistad de tu vida.",
            "Reinterpreta la parábola del Sembrador pensando en cómo recibes consejos hoy.",
            "Reinterpreta la parábola de la Levadura pensando en pequeñas acciones que generan gran cambio.",
            "Reinterpreta la parábola de los Dos Cimientos pensando en tus decisiones actuales.",
            "Reinterpreta la parábola del Fariseo y el Publicano pensando en la humildad hoy.",
            "Reinterpreta la parábola de las Diez Vírgenes pensando en la preparación para lo importante.",
            "Reinterpreta la parábola del Rico Insensato pensando en el consumismo actual.",
        ],
    },
    "fe_testimonio_breve": {
        "categoria": "fe",
        "titulo": "El testimonio breve",
        "prompts": [
            "Comparte un momento en que sentiste una ayuda que no esperabas.",
            "Comparte un momento en que una oración se sintió respondida.",
            "Comparte un momento en que alguien fue como una respuesta a una necesidad tuya.",
            "Comparte un momento en que sentiste paz en medio de una dificultad.",
            "Comparte un momento en que una 'coincidencia' se sintió como más que eso.",
            "Comparte un momento en que perdonaste algo que parecía imposible perdonar.",
            "Comparte un momento en que encontraste fuerza donde no creías tenerla.",
            "Comparte un momento en que una palabra o consejo llegó justo cuando lo necesitabas.",
            "Comparte un momento en que sentiste gratitud profunda de la nada.",
            "Comparte un momento en que decidiste confiar aunque no entendías todo.",
        ],
    },
    "fe_oracion_una_frase": {
        "categoria": "fe",
        "titulo": "La oración en una frase",
        "prompts": [
            "Resume en una frase lo que orarías hoy por ti mismo.",
            "Resume en una frase lo que orarías hoy por tu familia.",
            "Resume en una frase lo que orarías hoy por un amigo.",
            "Resume en una frase lo que orarías hoy por alguien que sufre.",
            "Resume en una frase lo que orarías hoy por tu comunidad o país.",
            "Resume en una frase lo que orarías hoy en agradecimiento.",
            "Resume en una frase lo que orarías hoy pidiendo sabiduría.",
            "Resume en una frase lo que orarías hoy pidiendo paciencia.",
            "Resume en una frase lo que orarías hoy por alguien con quien tienes un conflicto.",
            "Resume en una frase lo que orarías hoy por el futuro.",
        ],
    },
    "fe_personaje_biblico": {
        "categoria": "fe",
        "titulo": "El personaje bíblico",
        "prompts": [
            "Responde como si fueras David antes de enfrentar a Goliat: ¿qué sientes?",
            "Responde como si fueras Noé construyendo el arca: ¿qué te dice la gente?",
            "Responde como si fueras María recibiendo la noticia del ángel: ¿qué piensas?",
            "Responde como si fueras Jonás dentro del gran pez: ¿qué reflexionas?",
            "Responde como si fueras Pedro caminando sobre el agua: ¿qué sientes antes de dudar?",
            "Responde como si fueras Ester antes de hablar con el rey: ¿qué te da valor?",
            "Responde como si fueras el hijo pródigo volviendo a casa: ¿qué piensas en el camino?",
            "Responde como si fueras Moisés frente a la zarza ardiente: ¿qué le dirías a Dios?",
            "Responde como si fueras Rut decidiendo quedarse con Noemí: ¿por qué lo harías?",
            "Responde como si fueras uno de los discípulos en la última cena: ¿qué sientes?",
        ],
    },
    "fe_virtud_del_dia": {
        "categoria": "fe",
        "titulo": "La virtud del día",
        "prompts": [
            "Reflexiona sobre la paciencia: ¿cuándo la necesitas más en tu vida diaria?",
            "Reflexiona sobre la humildad: ¿cómo la practicas sin que se note demasiado?",
            "Reflexiona sobre la generosidad: ¿cuál fue tu último acto generoso, grande o pequeño?",
            "Reflexiona sobre el perdón: ¿qué te ha costado más perdonar?",
            "Reflexiona sobre la esperanza: ¿qué te da esperanza en tiempos difíciles?",
            "Reflexiona sobre la fidelidad: ¿en qué área de tu vida te esfuerzas por ser fiel?",
            "Reflexiona sobre la gratitud: ¿cómo la practicas en tu rutina diaria?",
            "Reflexiona sobre el amor al prójimo: ¿cómo lo mostraste esta semana?",
            "Reflexiona sobre la mansedumbre: ¿cuándo te cuesta más responder con calma?",
            "Reflexiona sobre la fe: ¿qué la fortalece más en tu vida?",
        ],
    },
    "fe_consejo_sabio": {
        "categoria": "fe",
        "titulo": "El consejo sabio",
        "prompts": [
            "Comparte un consejo basado en la paciencia que le darías a alguien impaciente.",
            "Comparte un consejo basado en el perdón que le darías a alguien resentido.",
            "Comparte un consejo basado en la humildad que le darías a alguien orgulloso.",
            "Comparte un consejo basado en la fe que le darías a alguien que duda.",
            "Comparte un consejo basado en la gratitud que le darías a alguien desanimado.",
            "Comparte un consejo basado en el amor que le darías a alguien que sufrió una traición.",
            "Comparte un consejo basado en la esperanza que le darías a alguien sin motivación.",
            "Comparte un consejo basado en la prudencia que le darías a alguien impulsivo.",
            "Comparte un consejo basado en la constancia que le darías a alguien que se rinde fácil.",
            "Comparte un consejo basado en el servicio que le darías a alguien egoísta sin sonar duro.",
        ],
    },
    "fe_bendicion_compartida": {
        "categoria": "fe",
        "titulo": "La bendición compartida",
        "prompts": [
            "Comparte una bendición corta para la persona a tu derecha (o la última que habló).",
            "Comparte un buen deseo para el año de alguien del grupo.",
            "Comparte una bendición para la familia de alguien del grupo.",
            "Comparte un buen deseo de salud para alguien del grupo.",
            "Comparte una bendición para los proyectos o metas de alguien del grupo.",
            "Comparte un buen deseo de paz para alguien que sabes que la necesita.",
            "Comparte una bendición para el camino o viaje de alguien del grupo.",
            "Comparte un buen deseo de sabiduría para alguien que enfrenta una decisión.",
            "Comparte una bendición para la amistad de todo el grupo.",
            "Comparte un buen deseo final para cerrar esta ronda de juegos con gratitud.",
        ],
    },
}
